In [2]:
import numpy as np
#Dimensions of X
n = 6
m = 5
r = 3
#Columns of X
c1 = np.expand_dims(np.array([1,1,0,0,0,0]), axis=1)
c2 = np.expand_dims(np.array([0,0,1,1,0,0]), axis=1)
c3 = np.expand_dims(np.array([0,0,0,0,1,1]), axis=1)
c4 = 2*c1+c2
c5 = c1+2*c2-3*c3

X = np.concatenate((c1,c2,c3,c4,c5), axis = 1)

#Create random projection matrices
P1 = np.random.randint(2, size = (n,r))
P1 = P1*2-np.ones((n,r))
P2 = np.random.randint(2, size = (n,r+1))
P2 = P2*2-np.ones((n,r+1))

P3 = np.random.randint(2, size = (m,r))
P3 = P3*2-np.ones((m,r))
P4 = np.random.randint(2, size = (m,r+1))
P4 = P4*2-np.ones((m,r+1))

#Project X onto P
Y1 = P1.T @ X
Y2 = P2.T @ X

Z1 = X @ P3
Z2 = X @ P4

print('Rank of Y1 = ' + str(np.linalg.matrix_rank(Y1)))
print('Rank of Y2 = ' + str(np.linalg.matrix_rank(Y2)))
print('Rank of Z1 = ' + str(np.linalg.matrix_rank(Z1)))
print('Rank of Z2 = ' + str(np.linalg.matrix_rank(Z2)))

Rank of Y1 = 2
Rank of Y2 = 3
Rank of Z1 = 3
Rank of Z2 = 3


In [3]:
#Dimensions of X
n = 1000
m = 500
r = 300
#Create r linearly independent columns
X = np.random.randint(5, size = (n,r))
rtest = np.linalg.matrix_rank(X)
print ('Rank of X = ' + str(rtest))
if r != rtest:
    raise Exception("Generated matrix does not have rank r")

#Add linearly dependent columns to X
Xorig = X
i = r
while i < m:
    coefs = np.random.randint(-1,2, size = (r,1))
    c = Xorig @ coefs
    X = np.concatenate((X,c), axis=1)
    i += 1;
    
print('Size of X is now ' + str(X.shape))
r = np.linalg.matrix_rank(X)
print('Rank of new X = ' + str(r))

#Randomly shuffle columns of X
np.random.shuffle(X.T)

#Create random matrcies of -1 and 1s
P1 = np.random.randint(2, size = (n,r))
P1 = P1*2-np.ones((n,r))
P2 = np.random.randint(2, size = (n,r+1))
P2 = P2*2-np.ones((n,r+1))

#Project X onto random matrices
Y1 = P1.T @ X
Y2 = P2.T @ X
print('Rank of Y1 = ' + str(np.linalg.matrix_rank(Y1)))
print('Rank of Y2 = ' + str(np.linalg.matrix_rank(Y2)))


P3 = np.random.randint(2, size = (m,r))
P3 = P3*2-np.ones((m,r))
P4 = np.random.randint(2, size = (m,r+1))
P4 = P4*2-np.ones((m,r+1))

Z1 = X @ P3
Z2 = X @ P4
print('Rank of Z1 = ' + str(np.linalg.matrix_rank(Z1)))
print('Rank of Z2 = ' + str(np.linalg.matrix_rank(Z2)))

Rank of X = 300
Size of X is now (1000, 500)
Rank of new X = 300
Rank of Y1 = 300
Rank of Y2 = 300
Rank of Z1 = 300
Rank of Z2 = 300


In [404]:
arr = np.arange(9).reshape((3, 3))
print(arr)
np.random.shuffle(arr.T)
arr

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])